# Version of docker-compose
version: '3'

# Containers
services:
  vuejs:
    build:
      context: ./webTimeManager
    ports:
      - '8080:8080'
  # Our Phoenix container
  phoenix:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: ./apiTimeManager
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://postgres@db5432/apitimemanager_dev
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    command: './entrypoint.sh'
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:
