name: actions
on: [push]

run:
  working-directory: ./apiTimeManager
  
jobs:
  test:
    runs-on: windows-latest

    env:
      MIX_ENV: test

    services:
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: 22.2.6
          elixir-version: 1.10.1
      - uses: actions/cache@v1
      - uses: actions/cache@v1
      - run: mix test
