name: actions
on: [push]

jobs:
  build:
    runs-on: windows-latest
    env:
      working-directory: ./apiTimeManager
    steps:
      - uses: actions/checkout@v2
        with:
          otp-version: 22.2.6
          elixir-version: 1.10.1
        working-directory: ./apiTimeManager
        - run: mix test 
