name: actions
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    container:
      image: adawalli/dockercompose:latest

    steps:
    - uses: actions/checkout@v1

    - name: Install Docker    
      run: |
      docker-compose build
