name: Docker & Mix 
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        docker-compose build
        docker-compose up
        defaults:  
      
      run:  
        working-directory: ./apiTimeManager
        - run: cd