name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: cd ./webTimeManager | npm test
    - run: cd ../apiTimeManager | mix test
      env:
        CI: true
