name: Node.js CI

on: [push]
defaults:
  run:
    working-directory: ./apiTimeManager

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: mix test       
    env:
      CI: true
